times = ('Palmeiras', 'Internacional', 'Fluminense', 'Flamengo', 'Corinthians', 'Athletico PR', 'Atlético-MG', 'América-MG', 'Goiás', 'São Paulo', 'Botafogo', 'Santos', 'Red Bull', 'Fortaleza', 'Ceará', 'Coritiba', 'Avaí', 'Cuiabá', 'Atlético-GO', 'Juventude')
print('-=' *20)
print('Lista de times do Brasileirão: ', times)
print('-=' *20)
print('Os cinco primeiros são: ', times[0:5])
print('-=' *20)
print('Os quatro últimos são: ', times[-4:])
print('-=' *20)
print('Times em ordem alfabética: ', sorted(times))
print('-=' *20)
print(f'O {times[7]} está na 8ª posição.')
print('-=' *20)